---
dns_servers:
  - 192.168.6.3

aaa_servers:
  - 1.1.1.1
  - 1.1.1.2

snmp_servers:
  - 192.168.6.9

ntp_servers:
  - 3.3.3.3
  - 3.3.3.4
  - 5.5.5.5
  - 6.6.6.6

syslog_servers:
  - 192.168.6.9

snmp_group: "SNMP_V3"
snmp_user: "snmp_admin"
snmp_password: "snmp_password"