default:
  image:
    name: amack07/gitlab-runner:v1
    entrypoint: [""]
before_script:
  - ansible-lint --version

stages:
  - ansible-lint
  - deploy-aaa
  - deploy-dns
  - deploy-ntp
  - deploy-snmp
  - deploy-syslog

ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint -v *.yml
  allow_failure: true

deploy-aaa:
  stage: deploy-aaa
  script:
    - 'curl -kX POST https://myansibletower.com/api/v2/job_templates/18/launch/ -H "Authorization: Bearer $TOWER_TOKEN"'
  only:
    changes:
      - "roles/config_aaa/**/*"

deploy-dns:
  stage: deploy-dns
  script:
    - 'curl -kX POST https://myansibletower.com/api/v2/job_templates/41/launch/ -H "Authorization: Bearer $TOWER_TOKEN"'
  only:
    changes:
      - "roles/config_dns/**/*"

deploy-ntp:
  stage: deploy-ntp
  script:
    - 'curl -kX POST https://myansibletower.com/api/v2/job_templates/17/launch/ -H "Authorization: Bearer $TOWER_TOKEN"'
  only:
    changes:
      - "roles/config_ntp/**/*"

deploy-snmp:
  stage: deploy-snmp
  script:
    - 'curl -kX POST https://myansibletower.com/api/v2/job_templates/29/launch/ -H "Authorization: Bearer $TOWER_TOKEN"'
  only:
    changes:
      - "roles/config_snmp/**/*"

deploy-syslog:
  stage: deploy-syslog
  script:
    - 'curl -kX POST https://myansibletower.com/api/v2/job_templates/23/launch/ -H "Authorization: Bearer $TOWER_TOKEN"'
  only:
    changes:
      - "roles/config_syslog/**/*"
