---
- name: Collect Network Facts
  hosts: all
  gather_facts: no

  tasks:
    - name: Obtain list of devices from Netbox
      debug:
        msg: "{{ item }}"
      loop: "{{ query('netbox.netbox.nb_lookup',
        'devices',
        api_endpoint='http://192.168.6.106/',
        api_filter='platform=eos',
        token= netbox_token) }}"
      delegate_to: localhost
      run_once: true
