---
- name: Configure base config on Nexus devices
  hosts: all
  gather_facts: no

  roles:
    - config_interfaces
    - config_provisioning
    - config_ntp
    - config_syslog
    - config_snmp
    - config_aaa