- name: Remove users and configure Admin password
  nxos_user:
    configured_password: "{{ global_pass }}"
    name: admin 
    state: present 
    purge: yes
 
- name: Configure SNMP User
  nxos_user:
    configured_password: "{{ snmp_password }}"
    name: "{{ snmp_user }}" 
    state: present 
    purge: yes