- name: Get Existing NTP Servers
  asa_command: 
    commands: "sh run | i ntp server"
  register: current_ntp

- name: Configure NTP Servers
  asa_config:
    src: templates/asa_ntp.j2
    replace: line

- name: Remove Unused NTP Servers
  asa_config:
    src: templates/asa_ntp_remove.j2
    replace: line
