- name: Get Existing NTP Servers
  nxos_command: 
    commands: "sh run | i 'ntp server'"
  register: current_ntp

- name: Configure NTP Servers
  nxos_config:
    src: templates/nxos_ntp.j2
    diff_against: running

- name: Remove Unused NTP Servers
  nxos_config:
    src: templates/nxos_ntp_remove.j2
    replace: line