- name: Configure Source Interface for Logging
  nxos_logging:
    interface: mgmt0
    state: present

- name: Configure Remote Logging
  nxos_logging:
    dest: server
    remote_server: "{{ item }}"
    facility: auth
    facility_level: 1
    use_vrf: management
    timestamp: milliseconds
    state: present
  loop: "{{ syslog_servers }}"
