- name: Set hostname
  bigip_hostname:
    hostname: "{{ inventory_hostname }}.macknet"
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Set F5 Banner
  bigip_sys_global:
    security_banner: yes
    banner_text: "{{ lookup('file', 'files/banner.txt') }}"
    provider: "{{ provider }}"
  delegate_to: localhost

- name: Change MGMT SSL Ciphers
  bigip_device_httpd:
    ssl_protocols:
      - "TLSv1.1"
      - "TLSv1.2"
    provider: "{{ provider }}"
  delegate_to: localhost
